# django_api/docker-compose.prod.yml

services:
  web:
    build: .
    # Este comando se ejecuta en producción: aplica migraciones y luego inicia Gunicorn
    command: >
      sh -c "python manage.py migrate && 
             gunicorn --bind 0.0.0.0:8000 wallet_project.wsgi:application"
    ports:
      - "8000:8000"
    # Las variables de entorno (POSTGRES_HOST, POSTGRES_PASSWORD, etc.)
    # serán inyectadas por Elastic Beanstalk desde la configuración de la consola.