services:
  db:
    image: postgres:15
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=cocolabs
      - POSTGRES_USER=coco
      - POSTGRES_PASSWORD=wallet
    ports:
      - "5432:5432"
    networks:
      - coco_network

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
    env_file:
      - ./.env
    dns:
      - 8.8.8.8
      - 8.8.4.4
    networks:
      - coco_network

networks:
  coco_network:
    driver: bridge

volumes:
  postgres_data: