service: serverless-wallet-api
frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-1
  environment:
    MONGO_URI: ${file(env.prod.yml):MONGO_URI}
    JWT_SECRET: ${file(env.prod.yml):JWT_SECRET}
    ETHERSCAN_API_KEY: ${file(env.prod.yml):ETHERSCAN_API_KEY}
    USDC_CONTRACT_ADDRESS: ${file(env.prod.yml):USDC_CONTRACT_ADDRESS}

plugins:
  - serverless-offline

functions:
  api:
    handler: handler.main
    events:
      - httpApi:
          path: /{proxy+}
          method: any